version: "3.7"

services:
  influxdb:
    image: "quay.io/influxdb/influxdb:2.0.0-beta"
    volumes:
      - "influxdb-data:/var/lib/influxdb"
    ports:
      - "9999:9999"
    network_mode: "bridge"
    
  influxdb-setup:
    image: "quay.io/influxdb/influxdb:2.0.0-beta"
    depends_on:
      - "influxdb"
    network_mode: "service:influxdb"
    command: "/bin/sh -c 'sleep 15 && influx setup \
      --bucket ${INFLUXDB_BUCKET} \
      --org ${INFLUXDB_ORG} \
      --username ${INFLUXDB_USER} \
      --password ${INFLUXDB_PASSWORD} \
      --token ${INFLUXDB_TOKEN} \
      --force '"
      
  datawriter:
    build:
      context: "./files"
    depends_on:
      - "influxdb-setup"
    network_mode: "service:influxdb"
    command: "/bin/sh -c 'sleep 15 && pip install -r requirements.txt && python mqttclient.py && python httpclient.py'"
    
volumes:
  influxdb-data:
